"""empty message

Revision ID: a6ecc2dafbbd
Revises: 
Create Date: 2022-06-14 12:51:14.970570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ecc2dafbbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name_surname', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('group', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'group')
    op.drop_column('user', 'name_surname')
    # ### end Alembic commands ###
